# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Build Configuration                       +
# project    nord-atom-syntax                                    +
# repository https://github.com/arcticicestudio/nord-atom-syntax +
# author     Arctic Ice Studio                                   +
# email      development@arcticicestudio.com                     +
# copyright  Copyright (C) 2017                                  +
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI
#   https://docs.travis-ci.com
# Atom CI
#   https://github.com/atom/ci
language: node_js
node_js:
  - "6"
  - "4"
env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
os:
  - linux
  - osx
cache: yarn
addons:
  apt:
    packages:
      - build-essential
      - git
      - libgnome-keyring-dev
      - fakeroot
notifications:
  email:
    on_success: never
    on_failure: change
before_script:
  - yarn global add gulp
  - yarn install
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - gulp --harmony lint
  - ./build-package.sh
