environment:
  APM_TEST_PACKAGES:
  ATOM_LINT_WITH_BUNDLED_NODE: "true"

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

version: "{build}"
platform: x64
test: off
deploy: off
